
import { GoogleGenAI, Modality } from "@google/genai";

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const fileToGenerativePart = (base64Data: string, mimeType: string) => {
  return {
    inlineData: {
      data: base64Data,
      mimeType,
    },
  };
};

export const generateHistoricalImage = async (
  base64Image: string,
  mimeType: string,
  scenePrompt: string
): Promise<string> => {
  const imagePart = fileToGenerativePart(base64Image, mimeType);
  const fullPrompt = `Take the person from the provided image and realistically place them in this historical scene or context: "${scenePrompt}". The final image should look like a plausible photograph from that era. Maintain the person's features and expression.`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        imagePart,
        { text: fullPrompt },
      ],
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return part.inlineData.data;
    }
  }

  throw new Error("No image was generated by the API.");
};
